name: "Auto Merge EIP"
description: "A bot that lints EIP edits, finds common errors, and can auto-merge"
inputs:
  GITHUB-TOKEN:
    description: |-
      The Github token to be used by this bot when merging, posting comments, or requesting reviewers
    required: true

runs:
  using: "composite"
  steps:
    - run: pwd && ls && cd .. && pwd && ls && cd .. && pwd && ls && cd _actions && pwd && ls && cd alita-moore && pwd && ls && EIP-Bot && pwd && ls && cd 1.0.4 && pwd && ls && npm ci && npm run build && GITHUB_TOKEN=${{ inputs.GITHUB-TOKEN }} node build/index.js
      shell: bash
