name: "Rerun Old Bot Run (pull_request_target) on review"
description: "This is a hack to avoid issues with secrets and non-clearing failed runs"
inputs:
  GITHUB-TOKEN:
    description: |-
      The Github token to be used by this bot when merging, posting comments, or requesting reviewers
    required: true

runs:
  using: "composite"
  steps:
    - run: cd ${{github.action_path}} && npm ci && npm run build && GITHUB_TOKEN=${{ inputs.GITHUB-TOKEN }} node build/index.js
      shell: bash
